### ISSUE TITLE
Cannot use root folder

### ISSUE THREAD

**Issue by FeikoJoosten** [Ratismal/DriveBackup#11]
I've tried to use the root folder as the main folder to create the backup with, and from there I wanted to add some blacklisting to make sure I do not accidentally add the server jar and stuff like that. However, I cannot seem to figure out the config key to use the root folder? Care to give me some assistance with that? 

This is using spiggot 1.14.2.

**Comment by RoboMWM** [comment]
Try `.` for current directory.

**Comment by FeikoJoosten** [comment]
Thanks for your quick response. 

I've tried the following options without success. 

`.:`
`..:`
`../:`
`..\:`
`/:`
`/:`
`:`
` :`

I've added in the `:` into my examples as that's required (afaik) for the config for a term to be recognized. With each change I first ran `drivebackup reloadconfig` to then follow it up with `drivebackup backup`.

Edit: serverlog when using `.:`:
Edit 2: formatting. 

```21.06 00:55:09 [Server] Server thread/INFO [DriveBackup] Forcing a backup.
21.06 00:55:09 [Server] Thread-15/INFO [DriveBackup] Creating backups, server may lag for a little while...
21.06 00:55:09 [Server] Thread-15/WARN Exception in thread "Thread-15" 
21.06 00:55:09 [Server] Thread-15/WARN java.lang.NullPointerException
21.06 00:55:09 [Server] Thread-15/WARN at ratismal.drivebackup.UploadThread.run(UploadThread.java:51)
21.06 00:55:09 [Server] Thread-15/WARN at java.lang.Thread.run(Thread.java:748)
21.06 00:55:09 [PebbleHost] Arfus ran command: Drivebackup backup
