### ISSUE TITLE
Metrics Fails to start on Latest 1.9 Spigot build

### ISSUE THREAD

**Issue by MrMoogles** [Ratismal/DriveBackup#5]
[04:10:27 WARN]: org.apache.commons.lang.UnhandledException: Plugin DriveBackup v1.0.7 generated an exception while executing task 12
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at ratismal.drivebackup.DriveBackup.Metrics.postPlugin(Metrics.java:335)
at ratismal.drivebackup.DriveBackup.Metrics.access$400(Metrics.java:57)
at ratismal.drivebackup.DriveBackup.Metrics$1.run(Metrics.java:223)
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

Looks like it's related to Metrics not having the correct getOnlinePlayers method.

User Zethrus reported in Spigot Forums:
https://www.spigotmc.org/threads/drivebackup.133344/#post-1425058

**Comment by RoboMWM** [comment]
Issue title is incorrect, the plugin is working just fine, just a Metrics thing which doesn't affect the plugin's functionality.

**Comment by MrMoogles** [comment]
Yea, figured it out after I actually looked into the error. Its all fixed now :)!
