### ISSUE TITLE
error after long backup

### ISSUE THREAD

**Issue by Wqrld** [Ratismal/DriveBackup#7]
i was waiting long for my backup to finish and then it said

org.apache.commons.net.io.CopyStreamException: IOException caught while copying.
[03:44:38] [Thread-49/WARN]:    at org.apache.commons.net.io.Util.copyStream(Util.java:134)
[03:44:38] [Thread-49/WARN]:    at org.apache.commons.net.ftp.FTPClient._storeFile(FTPClient.java:653)
[03:44:38] [Thread-49/WARN]:    at org.apache.commons.net.ftp.FTPClient.__storeFile(FTPClient.java:624)
[03:44:38] [Thread-49/WARN]:    at org.apache.commons.net.ftp.FTPClient.storeFile(FTPClient.java:1976)
[03:44:38] [Thread-49/WARN]:    at ratismal.drivebackup.ftp.FTPUploader.uploadFile(FTPUploader.java:54)
[03:44:38] [Thread-49/WARN]:    at ratismal.drivebackup.UploadThread.run(UploadThread.java:89)
[03:44:38] [Thread-49/WARN]:    at java.lang.Thread.run(Thread.java:745)
[03:44:38] [Thread-49/WARN]: Caused by: java.net.SocketException: Connection reset
[03:44:38] [Thread-49/WARN]:    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
[03:44:38] [Thread-49/WARN]:    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
[03:44:38] [Thread-49/WARN]:    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
[03:44:38] [Thread-49/WARN]:    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
[03:44:38] [Thread-49/WARN]:    at org.apache.commons.net.io.Util.copyStream(Util.java:111)
[03:44:38] [Thread-49/WARN]:    ... 6 more
File uploaded in 540.42 seconds (6769.58KB/s)
backup complete

sorry for the ...6 more its also in my logs
no crash
i think that 540 seconds for the backup for a plugins folder(i think it was even longer) was too long and i dont like these errors
the file did upload to my ftp(where i set it to)
can it be something with the file size?
the zipped file is 27.000.000 bytes

i hope u know what it is and that u can fix it

**Comment by Ratismal** [comment]
Large files are, unfortunately, going to take a long time to upload. This isn't limited by the plugin, but by your server's internet. I did that math, and 6769KB/s for 540s means that your backup is approximately 3.7GB large. This should be accurate because the duration is calculated by finding the difference between the start date and finish date, and the rate of uploading is then calculated based on that and the total file size. The fact of the matter is, a file of that size is going to take a long time to upload. It's a good thing you're not using OneDrive, because it's maximum rate of uploading is really slow!

I can understand the errors being irritating, especially if the files are in fact uploading correctly. I can add an option in the config to suppress these messages, but considering these errors are from upstream that's about as much as I can do.

Sorry I couldn't be more help!

**Comment by Wqrld** [comment]
i found the problem, it was just my ftp server being full

**Comment by Ratismal** [comment]
I'm glad that you found the issue!
